---
kind: pipeline
type: docker
name: "clang-9 armv7"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: clang-9
      CXX: clang++-9
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install clang-9 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv7a -mfpu=neon' -DCMAKE_CXX_FLAGS='-march=armv7a -mfpu=neon'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "clang-9 armv8"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: clang-9
      CXX: clang++-9
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install clang-9 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv8a' -DCMAKE_CXX_FLAGS='-march=armv8a'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "gcc-8 armv7"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: gcc-8
      CXX: g++-8
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install gcc-8 g++-8 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv7-a -mfpu=neon' -DCMAKE_CXX_FLAGS='-march=armv7-a -mfpu=neon'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "gcc-8 armv8"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: gcc-8
      CXX: g++-8
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install gcc-8 g++-8 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv8-a -mfpu=neon' -DCMAKE_CXX_FLAGS='-march=armv8-a -mfpu=neon'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "gcc-7 armv7"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: gcc-7
      CXX: g++-7
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install gcc-7 g++-7 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv7-a -mfpu=neon' -DCMAKE_CXX_FLAGS='-march=armv7-a -mfpu=neon'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "gcc-7 armv8"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: gcc-7
      CXX: g++-7
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install gcc-7 g++-7 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv8-a -mfpu=neon' -DCMAKE_CXX_FLAGS='-march=armv8-a -mfpu=neon'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "clang-7 armv7"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: clang-7
      CXX: clang++-7
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install clang-7 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv7a' -DCMAKE_CXX_FLAGS='-march=armv7a'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*

---
kind: pipeline
type: docker
name: "clang-7 armv8"
platform:
  os: linux
  arch: arm
steps:
  - name: test
    image: ubuntu:bionic
    environment:
      CC: clang-7
      CXX: clang++-7
    commands:
    - uname -m
    - cat /proc/cpuinfo
    - apt-get -yq update
    - apt-get -yq install clang-7 cmake git-core
    - git submodule update --init --recursive
    - mkdir test/build
    - cd test/build
    - cmake .. -DCMAKE_C_FLAGS='-march=armv8a' -DCMAKE_CXX_FLAGS='-march=armv8a'
    - make -j VERBOSE=1
    - ./run-tests
trigger:
  branch:
    exclude:
    - wip/*
